# realsense2_camera_node:
#   ros__parameters:
#     base_frame_id: base_link
#     enable_accel: true
#     enable_color: true
#     enable_depth: true
#     enable_gyro: true
#     enable_infra1: false
#     enable_infra2: false
#     enable_sync: true
#     publish_odom_tf: true
#     publish_tf: true
#     unite_imu_method: 2
#     use_sim_time: false

realsense2_camera_node2:
  ros__parameters:
    serial_no: '239722073171'
    base_frame_id: base_link
    enable_accel: false
    enable_color: true
    enable_depth: true
    enable_gyro: false
    enable_infra1: false
    enable_infra2: false
    enable_sync: true
    publish_odom_tf: false
    publish_tf: false
    unite_imu_method: 0
    use_sim_time: false
